//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş_Yönetim_sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class demirbas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public demirbas()
        {
            this.ustune_zimmet = new HashSet<ustune_zimmet>();
        }
    
        public string seri_no { get; set; }
        public string mac { get; set; }
        public int id { get; set; }
        public string kayit_kullanici_id { get; set; }
        public string adi { get; set; }
        public System.DateTime kayit_tarihi { get; set; }
    
        public virtual demirbas demirbas1 { get; set; }
        public virtual demirbas demirbas2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ustune_zimmet> ustune_zimmet { get; set; }
    }
}
