//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş_Yönetim_sistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class demirbasEntities1 : DbContext
    {
        public demirbasEntities1()
            : base("name=demirbasEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<demirbas> demirbas { get; set; }
        public virtual DbSet<ustune_zimmet> ustune_zimmet { get; set; }
        public virtual DbSet<departman> departman { get; set; }
        public virtual DbSet<personel> personel { get; set; }
        public virtual DbSet<view_PersonelDepartman> view_PersonelDepartman { get; set; }
        public virtual DbSet<view_ustunezimmet> view_ustunezimmet { get; set; }
    }
}
