//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş_Yönetim_sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public personel()
        {
            this.ustune_zimmet = new HashSet<ustune_zimmet>();
        }
    
        public string ad { get; set; }
        public string soyad { get; set; }
        public int durum { get; set; }
        public System.DateTime ise_baslangic { get; set; }
        public Nullable<System.DateTime> isten_cikis { get; set; }
        public int id { get; set; }
        public string kayit_kullanici_id { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> departman_Id { get; set; }
    
        public virtual departman departman { get; set; }
        public virtual departman departman1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ustune_zimmet> ustune_zimmet { get; set; }
    }
}
