//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş_Yönetim_sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ustune_zimmet
    {
        public int personel_id { get; set; }
        public int demirbas_id { get; set; }
        public System.DateTime zimmet_baslangic { get; set; }
        public Nullable<System.DateTime> zimmet_bitis { get; set; }
        public int id { get; set; }
        public string kayit_kullanici_id { get; set; }
        public Nullable<System.DateTime> kayit_tarihi { get; set; }
        public Nullable<int> durum { get; set; }
    
        public virtual demirbas demirbas { get; set; }
        public virtual personel personel { get; set; }
    }
}
