//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demirbaş_Yönetim_sistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_PersonelDepartman
    {
        public int id { get; set; }
        public int durum { get; set; }
        public System.DateTime baslangic { get; set; }
        public string adsoyad { get; set; }
        public string Adi { get; set; }
    }
}
